name: Deploy demo and PR previews to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, closed]

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || (github.event.action != 'closed' && github.event.action != 'deleted')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout gh-pages branch
        if: github.event_name == 'push'
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          fetch-depth: 0

      - name: Delete everything but pr-preview folder
        if: github.event_name == 'push'
        run: |
          find . -mindepth 1 -maxdepth 1 ! -name 'pr-preview' -exec rm -rf {} +

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Run install
        run: yarn install --frozen-lockfile

      - name: Build demo
        run: yarn build-demo

      - name: Delete contents of PR preview folder before publishing
        if: github.event_name == 'pull_request'
        run: |
          rm -rf pr-preview/pr-${{ github.event.pull_request.number }}/* || true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./demo/dist
          keep_files: true
          destination_dir: ${{ (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && './' || format('./pr-preview/pr-{0}', github.event.pull_request.number) }}

  delete-pr-preview:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && (github.event.action == 'closed' || github.event.action == 'deleted')
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          fetch-depth: 0

      - name: Remove PR preview folder
        run: |
          rm -rf pr-${{ github.event.pull_request.number }}

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Remove PR preview for #${{ github.event.pull_request.number }}"
          git push origin gh-pages
